### PR TITLE
add get_week_number_nexst() & update sotw_win_announcement

### PR DESCRIPTION
**Pull request by xknat**
@janvernieuwe kindly squash merge ^w^

### CODE REVIEW

**Review by Robin-M — COMMENTED** [review]
I don't see the reason making the same pull request as me (#64) but leaving out the case of starting on a different day. Your methods will give correct week numbers when started on a Sunday, but not when started on a Monday.

**Comment by xknat** [comment]
> I don't see the reason making the same pull request as me (#64) but leaving out the case of starting on a different day. Your methods will give correct week numbers when started on a Sunday, but not when started on a Monday.

welp, that just happens

**Comment by Robin-M** [comment]
If you ask me, if started on a Sunday the winner is for the current week and the new round is for the next week. If started on a Monday the winner is for the previous week and the new round is for the current week.

**Comment by xknat** [comment]
> If you ask me, if started on a Sunday the winner is for the current week and the new round is for the next week. If started on a Monday the winner is for the previous week and the new round is for the current week.

Good concept, I'll close this and review your pr

**Pull request closed without merging**
